### ISSUE TITLE
Column feature does not work so users do not know how to play music.

### ISSUE THREAD

**Issue by Nazar08** [n76/Symphony#10]
#### expected behavior
Some features should work so users can play music.

#### Real behavior
When the user runs the app and the user selects some features, the feature does not work, so the user can not play music.

#### How to reproduce
- Download the app in the f-droid.
- Run the app.
- select the feature column.
- column feature does not work and user does not know how to play music.
- Browser: symphony v1.1.3
- Operating system: xiomi redmi 4A, Android v6.0.1

#### Recording Of The Bug
https://youtu.be/W-gDtaA5sAE

**Comment by n76** [comment]
Symphony uses the list of playable media built up by Android's media manager. Is the media on your phone accessible from other players?

Depending on how music is added to the phone a reboot after adding the music may be necessary to trigger the media manager to rescan.

**Comment by n76** [comment]
No reply back on conditions that cause the music on the phone to not show up.
