### ISSUE TITLE
Unable to select other songs covered by current Music

### ISSUE THREAD

**Issue by Olamatto** [n76/Symphony#11]
#### Expected behavior
The app ought give easy access to select all listed music.

#### Actual Behavior 
Current music does not allow me click on other music,  it covers the music listed below

#### How to reproduce
- Download and install the application [here](https://f-droid.org/repository/browse/?fdid=net.gsantner.markor)
- Lunch the application 
- Select an album
- Then select the music
- Try select another music under the same album

But the current playing music, will not allow selecting next music 
<hr>

Application version: v 1.1.3
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/zeR-9siv1Ik

**Comment by n76** [comment]
Back button will hide the music controller an allow you to select the last track to play.

I'll leave this open to mark that the list of tracks and the music controller should not overlap.
