### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [n76/Symphony#12]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions (FAQ) for users self-service. Would love to hear from you, thanks

**Comment by n76** [comment]
That would be wonderful. I will consider any pull request you submit on this.

Thanks!

**Comment by olayhemy** [comment]
Thanks for the response!

I've submitted a pull request, kindly merge! 

Thanks.

**Comment by n76** [comment]
Fixed via e52daad61e7bbf39f063f6878554261bf3958ce2 and 18f69d6c2401d5e5af6b3da0d5be862e783a0c62
