### ISSUE TITLE
privacy policy

### ISSUE THREAD

**Issue by HarryHeights** [n76/Symphony#14]
Hello, I'm Harry. I contribute to open source projects by creating or drafting some needful documents such as privacy policy, about us etc. 
Privacy policy document is a way of openly declaring to end users your policies towards their privacy when they utilize your software.

If you feel this is needed, please let me know so I can create the document.

Thanks for your time

**Comment by n76** [comment]
A draft privacy document would be welcomed.

For what it is worth, the app itself does not report usage. The only data it stores on the phone is the play mode and current track information. This is so you can resume play when the app is (re)started. Play history, needed for the skip back function, is kept in RAM only and not stored.

And the distribution (F-Droid, etc.) doesn't collect data. At least not data I have access to. So a fair privacy statement might be that Symphony does not collect nor report usage or user data.


On August 8, 2018 10:10:54 PM GMT+05:30, Harry <notifications@github.com> wrote:
>Hello, I'm Harry. I contribute to open source projects by creating or
>drafting some needful documents such as privacy policy, about us etc. 
>Privacy policy document is a way of openly declaring to end users your
>policies towards their privacy when they utilize your software.
>
>If you feel this is needed, please let me know so I can create the
>document.
>
>Thanks for your time
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/n76/Symphony/issues/14

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by HarryHeights** [comment]
Alright. Thanks a lot for the information. I was gonna ask, I guess you read my mind. I'll draft the document right away.

**Comment by n76** [comment]
Take your time. . . I am 12 timezones away from home and my computer so it will be a while before I can easily review and pull or merge anything.

On August 9, 2018 12:29:41 PM GMT+05:30, Harry <notifications@github.com> wrote:
>Alright. Thanks a lot for the information. I was gonna ask, I guess you
>read my mind. I'll draft the document right away.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/n76/Symphony/issues/14#issuecomment-411657506

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by HarryHeights** [comment]
Okay alright. What 12 timezones away from home?? That's funny.  I guess you are having a holiday in the Bahamas.

**Comment by n76** [comment]
Current time at home is -7 and I am at +5.5, so it is actually 12.5 hours. That should narrow down the continents for you.

On August 9, 2018 1:13:01 PM GMT+05:30, Harry <notifications@github.com> wrote:
>Okay alright. What 12 timezones away from home?? That's funny.  I guess
>you are having a holiday in the Bahamas.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/n76/Symphony/issues/14#issuecomment-411667744

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by HarryHeights** [comment]
Hello, Are you back home now so I can make a PR for review?

**Comment by n76** [comment]
Send a PR whenever you would like.

**Comment by n76** [comment]
Added privacy policy to project documents.
