### ISSUE TITLE
Bug on previous button. 

### ISSUE THREAD

**Issue by darewealth** [n76/Symphony#19]
### Describing the Bug:
When I click on the ''previous'' icon while playing music, it didn't work

### To Reproduce:
* Launch the app

* Play any music 

* Click the previous icon

* Note the bug

### Expected Behavior:
I expected that the ''previous'' icon button should work and play the previous music when I clicked on it

### Recording Of The Bug
https://youtu.be/eo6qGQp2R1Q

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [1.1.10]

#### Additional information (Should in case)

The ''previous icon'' works sometimes. I've used it several times so the behavior is an off and on issue. Note that it might work on the first trial. try it over and over again and you will notice my point.

**Comment by n76** [comment]
Seems like you are trying to go back from the first track played. Is that correct?

At present, the app keeps a stack list of the previous tracks and simply pops the stack. But if the stack is empty there is nothing to go back to so the back button does nothing in that case.

If the above is correct then the question is, what should be the track previous to the first played?

Also, in you opinion, what should be the behavior of the back button with respect to where you are within a track. That is, should the back button take you to the beginning of the current track if you are significantly into the track which might then require two presses to go to a previous track.

**Comment by darewealth** [comment]
I think you should just try it on the said device. The previous button works somethings but fails to work most of the times  I tried to use it. I am certain about this behavior. Perhaps, the video shows I played music, next to the next music, then I tried to go back to the played music.

**Comment by n76** [comment]
> I think you should just try it on the said device.

I have one Android phone. In a pinch, I might be able to borrow a phone from a family member or friend. To the best of my knowledge, none of the people I know have this device.
