### ISSUE TITLE
[ Symphony version 1.1.10 ] the application is crash when i click  on the next songs button

### ISSUE THREAD

**Issue by XAMIR555** [n76/Symphony#21]
#### Project Information
* Repository------------------:[[Here]](https://github.com/n76/Symphony)
* Project Name--------------: [[Symphony]](https://f-droid.org/packages/org.fitchfamily.android.symphony/)
* Publisher-------------------: [[n76]](https://github.com/n76)
* My GitHub account-----:  [[Here]](https://github.com/XAMIR555)

#### Expected behavior
the  application [ Symphony version 1.1.10 ] should not be crash when I click on the next songs button

#### Actual behavior
the application is crash when i click  on the next songs button

#### How to reproduce
* [[ Download ] the application ](https://f-droid.org/packages/org.fitchfamily.android.symphony/)
* [ open the application ]
* click on the [ Next Songs Button ] 
* Note the Bug
* Browser/App version-:[1.1.10 ] 
* Operating system----:[8.0.0] 

#### Recording Of The Bug
![20190430_164036.gif](https://ipfs.busy.org/ipfs/QmSuWfjPo8ou1e3AydgL1sovXFXob8PS3L1rJUnSyoqSDv)

# Logcat

<pre><code>04-30 16:39:16.624 18543 18543 E AndroidRuntime: Process: org.fitchfamily.android.symphony, PID: 18543
04-30 16:39:16.624 18543 18543 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:34)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View.performClick(View.java:6291)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24931)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:808)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:101)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:25)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 9 more
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.e(Unknown Source:6)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.k(Unknown Source:23)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.l(Unknown Source:2)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(Unknown Source:7)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 11 more
</code></pre>

**Comment by n76** [comment]
One fix for crash on next button is fixed in 1.1.12. However your screen shot shows something a bit different.

Unfortunately, I don't see anything in your logcat that relates to the this app. Are you sure you've captured the correct portion of the logcat? There should be some reference to "symphony" and/or "org.fitchfamily.android.symphony" in the crash.

**Comment by XAMIR555** [comment]
sorry, sir, I capture wrong Logcat here is correct logcat


<pre><code>04-30 16:39:16.624 18543 18543 E AndroidRuntime: Process: org.fitchfamily.android.symphony, PID: 18543
04-30 16:39:16.624 18543 18543 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:34)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View.performClick(View.java:6291)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24931)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:808)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:101)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:25)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 9 more
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.e(Unknown Source:6)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.k(Unknown Source:23)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.l(Unknown Source:2)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(Unknown Source:7)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 11 more
</code></pre>

**Comment by n76** [comment]
It would be nice if the release build actually had good line numbers. :)

Anyway, I think I've found a the error. Could you please try the debug build I've temporarily placed at https://www.fitchfamily.org/Public/Symphony-debug.apk to see if that fixes it for you.

Thanks!

**Comment by XAMIR555** [comment]
this error  is still available in the  latest application  version ( 1.1.12 )


# Bug  GIF
![20190430_214135](https://user-images.githubusercontent.com/49812927/56978913-70b32600-6b2d-11e9-84d1-63d3d86f0ee9.gif)


# Logcat latest application version ( 1.1.12 )
<pre><code>04-30 16:39:16.624 18543 18543 E AndroidRuntime: FATAL EXCEPTION: main
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Process: org.fitchfamily.android.symphony, PID: 18543
04-30 16:39:16.624 18543 18543 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:34)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View.performClick(View.java:6291)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24931)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:808)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:101)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:25)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 9 more
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.e(Unknown Source:6)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.k(Unknown Source:23)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.l(Unknown Source:2)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(Unknown Source:7)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 11 more
</code></pre>

**Comment by n76** [comment]
If you try the debug version I posted earlier located at https://www.fitchfamily.org/Public/Symphony-debug.apk, it should either: 1. Not fail (if I've got the error figured out). Or 2. Show me line numbers in my current source.

**Comment by XAMIR555** [comment]
still available the crashing error in the latest application version  ( 1.1.12 )
sir according to  my information released more latest version like ( 1.1.13 ) maybe error become fixed

# Bug GIF
![20190501_112502](https://user-images.githubusercontent.com/49812927/57007830-65e5a900-6ba0-11e9-8630-bc637fec639b.gif)

# according to my knowledge read this line becarefull
>05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.playNext(MusicService.java:662)
05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.playNext(MainActivity.java:398)


# Maybe this Logcat helpful for you 
<pre><code>05-01 11:21:59.031 29599 29599 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.prepareTrack(MusicService.java:672)
05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.playNext(MusicService.java:662)
05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.playNext(MainActivity.java:398)
05-01 11:21:59.031 29599 29599 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(MainActivity.java:505)
11:22:02.421 29661 29661 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
05-01 11:22:02.421 29661 29661 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
05-01 11:22:02.421 29661 29661 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.prepareTrack(MusicService.java:672)
05-01 11:22:02.421 29661 29661 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.playNext(MusicService.java:662)
05-01 11:22:02.421 29661 29661 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.playNext(MainActivity.java:398)
05-01 11:22:02.421 29661 29661 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(MainActivity.java:505)
</code></pre>
















# Logcat

<pre><code>04-30 16:39:16.624 18543 18543 E AndroidRuntime: FATAL EXCEPTION: main
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Process: org.fitchfamily.android.symphony, PID: 18543
04-30 16:39:16.624 18543 18543 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:34)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View.performClick(View.java:6291)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24931)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:808)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:101)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater$a.onClick(Unknown Source:25)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	... 9 more
04-30 16:39:16.624 18543 18543 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.e(Unknown Source:6)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MusicService.k(Unknown Source:23)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.l(Unknown Source:2)
04-30 16:39:16.624 18543 18543 E AndroidRuntime: 	at org.fitchfamily.android.symphony.MainActivity.skipForward(Unknown Source:7)
</code></pre>

**Comment by n76** [comment]
Okay, I've put a check in that should keep this crash from happening. You can find a test version at https://www.fitchfamily.org/Public/Symphony-debug-2.apk Please let me know if that fixes it for you.

I am curious about your setup/phone. . . The media manager is apparently returning a genre but when asked about music tracks in that genre does not return any that this app can use. I've not seen that before and am not sure how that can happen. Did you have some classical music at one time and then remove it all? That might create a genre with no entries.

**Comment by XAMIR555** [comment]
Thank you very much now that's  error has been fixed 

![20190502_112803](https://user-images.githubusercontent.com/49812927/57059306-8d547880-6c69-11e9-8841-e4f4dbd6a1ec.gif)


I appreciate your work
