### ISSUE TITLE
Tagging scheme: v1.1.2 or 1.1.2?

### ISSUE THREAD

**Issue by relan** [n76/Symphony#7]
Hi,

F-Droid maintainer here. Could you please clarify whether "v" prefix of the latest tag is a typo or a new tagging scheme? This is important for F-Droid autoupdate mechanism.

**Comment by n76** [comment]
It the convention I've been using on my other projects so it slipped in here. I guess I ought to be consistent across the board, so going forward I'll use the "v" prefix.

**Comment by relan** [comment]
F-Droid will check tags with "v" prefix now on. Thanks!
