### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mansya** [n76/Symphony#8]
Hi @n76, I am a graphic designer, I want to help others in graphic design.

After I review your project, your logo is just a crop photo on this project. Therefore I would like to contribute to this project by creating a more interesting new logo / icon.

**Comment by n76** [comment]
Here is a [link to a concept that I thought might work for a logo](https://www.dropbox.com/s/7gzrn6rxj2hb4a2/viiolin-icon.zip?dl=0). But the shape was never finalized nor color(s) selected. Feel free to use that as a starting point or come up with something else (with suitable copyright status) on your own.

**Comment by mansya** [comment]
I've created a logo, with different colors, what do you think? which one do you like?
![symphony](https://user-images.githubusercontent.com/33461607/40445076-503b2200-5ef5-11e8-8e28-92f80b1b407f.png)

**Comment by n76** [comment]
The app was create for the classical music listener and I think of a classical music listener as an adult.

I like the overall shape but don't see a color I like. This set of colors seems child like to me.

Maybe a deeper or more saturated color would be more appropriate. I prefer cool colors to warm colors for this icon. Possibly in some deeper shade of blue or purple.

**Comment by TacoTheDank** [comment]
who says children don't like classical music? :^)

**Comment by mansya** [comment]
I have changed the logo, with different colors, what do you think? which one do you like? Choose the one you like!
![variation color](https://user-images.githubusercontent.com/33461607/40465115-50ede42c-5f49-11e8-80c6-9154de402134.png)

**Comment by n76** [comment]
Lets go with B.

Can you make the icon files or should I do them from your sample?

Thank you for your time, work and expertise!

**Comment by mansya** [comment]
Hi @n76 , I've uploaded logo and icon files to the drive, here's the link.
https://drive.google.com/open?id=1M4FWbhTFEkqnZpASOgtew5Gl_FA1cEMt

And I've sent a pull request for you.

**Comment by n76** [comment]
Do you have a svg (or eps) of just the logo itself, not on a background or with extra text?

That would allow me to use some standard tools to import the icon/logo into the app itself.

Thanks!

**Comment by mansya** [comment]
yes. I have uploaded it on the google drive's link

**Comment by n76** [comment]
Figured out how to extract the logo/icon object out of the files. As long as it looks good to you, no need for further action. If I've done it wrong, then please reopen this issue.

Thank you for the nice icon!
